name: flutter_app_updater
description: Package to handle app force update
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  package_info: ^0.4.1
  version: ^1.2.0
  firebase_remote_config: ^0.3.1
  rxdart: ^0.24.0
  get_it: ^1.0.3
  url_launcher: ^5.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
